# -*- python -*-
#
# Copyright 2022 Stéphane Caron

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "overview-simple",
    srcs = ["overview-simple.py"],
    main = "overview-simple.py",
    deps = [
        "@pip_bazel_pinocchio//pypi__pin",
    ],
)
