# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "overview-simple",
    srcs = ["overview-simple.cpp"],
    deps = [
        "@pinocchio",
    ],
)
