# -*- python -*-
#
# Copyright 2022 Stéphane Caron

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "overview-simple",
    srcs = [
        "overview-simple.cpp",
    ],
    deps = [
        "@pinocchio",
    ],
)
