name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    run_linux:
        name: "Run example on Linux"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Install dependencies"
              run: |
                  sudo apt install libboost-filesystem-dev libboost-serialization-dev libboost-system-dev libeigen3-dev liburdfdom-dev

            - name: "Run example"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk run --compilation_mode=fastbuild //examples/cpp:overview-simple

    ci_success:
        name: "CI success"
        runs-on: ubuntu-latest
        needs: [run_linux]
        steps:
            - run: echo "CI workflow completed successfully"
